In [65]:
import kagglehub
import pandas as pd
import numpy as np
from kagglehub import KaggleDatasetAdapter
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [66]:
# Download latest version
path = kagglehub.dataset_download("zahranusratt/e-commerce-orders-and-sales-performance-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'e-commerce-orders-and-sales-performance-dataset' dataset.
Path to dataset files: /kaggle/input/e-commerce-orders-and-sales-performance-dataset


In [67]:
full_file_path = f"{path}/ecommerce_sales_data (2).csv"
df = pd.read_csv(full_file_path)
df.head()

Order Date Product Name     Category Region  Quantity  Sales  Profit
0  2024-12-31      Printer       Office  North         4   3640  348.93
1  2022-11-27        Mouse  Accessories   East         7   1197  106.53
2  2022-05-11       Tablet  Electronics  South         5   5865  502.73
3  2024-03-16        Mouse  Accessories  South         2    786  202.87
4  2022-09-10        Mouse  Accessories   West         1    509  103.28

In [75]:
y = df["Region"]
X = df.drop("Region", axis=1)
X = X.drop("Order Date", axis=1)
X = pd.get_dummies(X, columns=['Product Name', 'Category'], drop_first=True)

In [87]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [77]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [78]:
scaler = StandardScaler()
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [79]:
y_pred = knn.predict(X_test)

In [88]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred, zero_division=0))

Accuracy: 0.2342857142857143
Confusion Matrix:
 [[56 47 39 36]
 [58 40 46 32]
 [55 44 47 25]
 [55 46 53 21]]
Classification Report:
               precision    recall  f1-score   support

        East       0.25      0.31      0.28       178
       North       0.23      0.23      0.23       176
       South       0.25      0.27      0.26       171
        West       0.18      0.12      0.15       175

    accuracy                           0.23       700
   macro avg       0.23      0.23      0.23       700
weighted avg       0.23      0.23      0.23       700

